server:
  port: 8799
  
spring:
   application: 
    name: zuulGateway 
    
    
eureka:
      instance:
        hostname: localhost

      client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://${eureka.instance.hostname}:8761/eureka/
          


#this below configuration is used in order to expose routes
# bcoz in updated version greater than 2.0.x  it need to be expose otherwise we will not able to see routes
# we can use "routes" in place of * below i.e(in place of include: '*')
management: 
  endpoints: 
    web: 
      exposure: 
        include: '*'